# Generated by Django 4.1.3 on 2022-11-27 13:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('origin_country', django_countries.fields.CountryField(max_length=2)),
                ('origin_province', models.CharField(max_length=50)),
                ('origin_city', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('sector', models.CharField(choices=[('media', 'Media'), ('cultuur', 'Cultuur'), ('particulier', 'Particulier'), ('onderwijs', 'Onderwijs'), ('welzijn', 'Welzijn')], default='media', max_length=50)),
                ('medium_foto', models.IntegerField()),
                ('medium_digitalfoto', models.IntegerField()),
                ('medium_document', models.IntegerField()),
                ('medium_reclame', models.IntegerField()),
                ('medium_film', models.IntegerField()),
                ('medium_audio', models.IntegerField()),
                ('medium_digitalarchive', models.IntegerField()),
                ('medium_objectfoto', models.IntegerField()),
            ],
        ),
    ]
