# Generated by Django 4.1.3 on 2022-11-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_imagerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_audio',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_digitalarchive',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_digitalfoto',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_document',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_film',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_foto',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_objectfoto',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_reclame',
            field=models.IntegerField(blank=True),
        ),
    ]
