# Generated by Django 4.1.3 on 2022-11-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_imagerequest_medium_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_digitalarchive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_digitalfoto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_document',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_film',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_foto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_objectfoto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_reclame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='origin_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='origin_province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
