# Generated by Django 4.1.3 on 2022-11-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_imagerequest_medium_digitalarchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='medium_audio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
