# Generated by Django 4.1.3 on 2022-11-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_imagerequest_medium_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
