# Generated by Django 4.1.3 on 2022-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequest',
            name='idnumber',
            field=models.CharField(default='BAYYYY-###', max_length=10),
        ),
    ]
