# Generated by Django 4.1.3 on 2022-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_imagerequest_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='idnumber',
            field=models.CharField(default='BA2022-###', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='year',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
