# Generated by Django 4.1.3 on 2022-11-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_imagerequest_idnumber_alter_imagerequest_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(default='BU2022-###', max_length=10, unique=True)),
                ('year', models.DateField(default='YYYY-MM-DD')),
                ('bug', models.CharField(choices=[('spin', 'Spin'), ('mot', 'Mot'), ('kleermot', 'Kleermot'), ('vlieg', 'Vlieg'), ('pissebed', 'Pissebed'), ('fruitvlieg', 'Fruitvlieg'), ('mug', 'Mug'), ('vliegendemier', 'Vliegende mier')], default='spin', max_length=50)),
                ('room', models.CharField(choices=[('opstaan', 'Opstaan'), ('geboorte', 'Geboorte'), ('verhuizen', 'Verhuizen'), ('rustdag', 'Rustdag'), ('ongeluk', '(on)geluk'), ('rouwen', 'Rouwen'), ('ouder', 'Ouder'), ('trappenhal', 'Trappenhal'), ('jong', 'Jong'), ('vakantie', 'Vakantie'), ('school', 'School'), ('trouw', 'Trouw'), ('avond', 'Avond'), ('huishouden', 'Huishouden'), ('spelen', 'Spelen')], default='spin', max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
